### ISSUE TITLE
contrib-slider: slider causes freeze on bookmarking

### ISSUE THREAD

**Issue by effernity** [adaptlearning/adapt_framework#1394]
Hello. 
The course hangs on load, when the bookmarking is on. Tested in Google Chrome and IE11.
The problem is, when the slider question is completed, on bookmarking there's an error:
IE:
```
> SCRIPT5007: Unable to get value of the property 'prop': object is null or undefined
> adapt.min.js, string: 84, column: 2306
```

Chrome:
```
Uncaught TypeError: Cannot read property 'prop' of undefined
at B.n.setAllItemsEnabled (adapt.min.js:84)
at B.n.disableQuestion (adapt.min.js:84)
at B.n.onEnabledChanged (adapt.min.js:83)
at b (adapt.min.js:76)
at v (adapt.min.js:76)
at d (adapt.min.js:76)
at B.n.u.trigger (adapt.min.js:76)
at B.n.set (adapt.min.js:76)
at B.n.set (adapt.min.js:77)
at B.n.setQuestionAsSubmitted (adapt.min.js:81)
```

There is loading circle and nothing happens.
![e5643aa4-e25c-11e6-9fd6-7c920a0530a5](https://cloud.githubusercontent.com/assets/20191947/22254055/9d951e48-e264-11e6-9658-9c8ffd1a1cc4.png)

**Comment by moloko** [comment]
@effernity could you just confirm what version of the framework (package.json), slider and spoor (both bower.json) you are using?

**Comment by effernity** [comment]
@moloko I'm using Adapt Authoring tool
package.json:
```
  "name": "adapt_framework",
  "version": "2.0.7",
  "description": "Adapt Learning output framework",
```
but version.js says:
```
    "adapt_authoring": "v0.2.2",
    "adapt_framework": "v2.0.16"
```
slider bower.json:
```
  "version": "2.1.3",
  "framework": "^2.0.13",
```
spoor bower.json:
```
  "version": "2.0.14",
  "framework": "^2.0.13",
```
also, bookmarking bower.json:
```
  "version": "2.0.4",
  "framework": "^2.0.0",
```

**Comment by moloko** [comment]
Not quite sure why that first one says 2.0.7, never mind though all the others indicate that you're thoroughly up-to-date, which is good.

I'll have a try myself tomorrow to see if I can replicate.

I don't think it's anything to do with the bookmarking extension as all that does is record where the user currently is within the course so that it can give the user the option to return to that location when they relaunch. 

The problem most likely lies in the spoor (SCORM tracking) extension - I suspect if you switch off `_shouldStoreResponses` (in the authoring tool it's Configuration settings > Extensions > Spoor > Store responses) then it will make the error go away - could be a good short term fix. This setting only needs to be enabled if you need the course to remember & restore the user's responses to questions between sessions.

**Comment by effernity** [comment]
The problem is that i need to remember user's responses :(
Although, I'll try this tomorrow.

**Comment by moloko** [comment]
fair enough, leave it with me - hopefully it will be something simple ;-)

**Comment by moloko** [comment]
OK well I just tried this out on a fresh copy of the framework... I can't seem to replicate in either IE11 or Chrome.

It sounds from your description like it's [this issue](https://github.com/adaptlearning/adapt_framework/issues/1308) but that was fixed in [Slider v2.1.2](https://github.com/adaptlearning/adapt-contrib-slider/releases/tag/v2.1.2)...

**Comment by effernity** [comment]
There is an error in PR, that fixed it in 2.1.2, @ntorgov referenced

**Comment by tomgreenfield** [comment]
I have also tested this and can confirm it was fixed in v2.12, as @moloko has referenced.

**Comment by effernity** [comment]
Well, I still have the issue.

**Comment by tomgreenfield** [comment]
Sorry to hear you're still having issues.

The Chrome error seems to indicate that `$this.slider` is undefined which is curious since it's already wrapped in a truthy conditional statement.

Would it be possible for you to attach a ZIP of your source code?

**Comment by effernity** [comment]
It's very confusing, but it seems, that recreating the slider resolved the issue.
I have an old scorm package, that contains old slider. Unfortunately, I don't have old zip of source code.
Maybe in this package was something wrong.
Anyway, I'm sorry for confusing you.
[testold.zip](https://github.com/adaptlearning/adapt_framework/files/735229/testold.zip)

**Comment by tomgreenfield** [comment]
Yes, your ZIP indeed shows you were on a version of Slider that is pre-2.1.2. Are you okay to close this issue?

**Comment by effernity** [comment]
Yes, sure, thank you a lot!
