### ISSUE TITLE
bug: android chrome timeout throttling

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1591]
https://bugs.chromium.org/p/chromium/issues/detail?id=570845

issue: with the updated media component timeouts are being excessively throttled for all of adapt code
impact: onscreen/inview and resize callbacks are delayed or missed
result: trickle show + hide of autohide button is severely delayed on android
solution: move to requestAnimationFrame instead of setTimeout where applicable in both jquery.resize and jquery.onscreen

**Comment by moloko** [comment]
@oliverfoster I've got a few queries about this...
* what 'updated media component'?
* the [chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=570845) you link to is very old, it was opened in Dec '15 and closed + fixed in Jan '16
* if this is high priority should it not be fixed for the current 2.1.x version? You have added it to the #1571 which indicates that it should be left for the v3 release

**Comment by oliverfoster** [comment]
* https://github.com/mediaelement/mediaelement/compare/2.16.3...2.22.1 media element has had a lot of changes since I wrote inview back in 2015, some of which are negatively impacting performance on android (especially on a page with lots of media components)
* that bug may be "fixed" but the throttling is still present on android https://bugs.chromium.org/p/chromium/issues/detail?id=570845#c19
* I have written the fix already I just need to PR it in I will get it in for 2.1.x, it definitely needs to be in before we drop transition to v3 - it was a misunderstanding on the intention of the ie8 epic on my part. I'll remove it from there.

**Comment by moloko** [comment]
@oliverfoster gotcha, thanks for the clarifications!
